package authservice.entities;

import jakarta.persistence.*;
import lombok.*;

@Entity // Marks the class as a JPA entity, meaning it corresponds to a table in the database.
@Data // Lombok annotation to automatically generate getters, setters, and other utility methods like equals and hashCode.
@ToString // Lombok annotation to automatically generate a toString method.
@NoArgsConstructor // Lombok annotation to generate a no-arguments constructor.
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields as parameters.
@Table(name = "roles") // Specifies the table name in the database that this entity maps to.
public class UserRole {

    @Id // Marks this field as the primary key of the table.
    @GeneratedValue(strategy = GenerationType.AUTO) // Specifies that the primary key is auto-generated by the database.
    @Column(name = "role_id") // Specifies that this field maps to the 'role_id' column in the 'roles' table.
    @Getter
    @Setter
    private long roleId; // The unique identifier for the user role.

    private String name; // The name of the role (e.g., "USER", "ADMIN").
    // Constructor
    public UserRole(String name) {
        this.name = name;
    }

    // Getter for name
    public String getName() {
        return name;
    }

}
