spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/authservice
    username: akshat
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            type:
              mapping:
                auth: authservice.model.UserInfoEvent
    topic-json:
      name: user_service

server:
  port: 9010

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG

security:
  basic:
    enable: false
  secret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
  ignored: /**
