_format_version: "2.1"
_transform: true

services:
  - name: expense-service
    url: http://expense-service.myapp.local:8080
    routes:
      - name: expense-route
        paths:
          - /api/v1/expenses
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://auth-service.myapp.local:9898/auth/v1/ping"

  - name: auth-service
    url: http://auth-service.myapp.local:9010
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
        preserve_host: false
