spring:
  application:
    name: expense-service

  datasource:
    url: jdbc:mysql://localhost:3306/expenseservice
    username: akshat
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"
    consumer:
      group-id: expense-info-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: expense.consumer.ExpenseDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: expense.dto.ExpenseDto
    topic-json:
      name: expense_service

server:
  port: 8080

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG


security:
  basic:
    enable: false
  ignored: /**