spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: akshat
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: userinfo-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: userservice.deserializer.UserInfoDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: userservice.entities.UserInfoDto

    topic-json:
      name: user_service

server:
  port: 9810

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG

security:
  basic:
    enable: false
  ignored: /**
